language: node_js
node_js:
  - "stable"
script:
  - npm install
  - npm run lint
  - npm test
  - npm run build
after_success: npm run coverage && codecov
skip_cleanup: true
on:
  branch: dev
env:
  REACT_APP_SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
  REACT_APP_SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}