export const SET_ALBUM = 'SET_ALBUM';

export const ADD_RECENT_ALBUM = 'ADD_RECENT_ALBUM';

export const SET_SEARCH = 'SET_SEARCH';

export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';

export const ADD_RECENT_RESULTS = 'ADD_RECENT_RESULTS';
